export interface Patent {
  patent_number: string
  title: string
  assignee: string
  snippet: string
  publication_date: string
  source: string
  url: string
  country: string
  detail_text?: string
}

export type Step = 'input' | 'patents' | 'report' | 'document'

/** AI 从 VOC 拆解出的单个搜索角度 */
export interface SearchStrategy {
  angle: string      // 中文角度说明
  query: string      // 英文搜索关键词
  rationale: string  // 为什么从这角度搜
}

export interface SearchResponse {
  keywords: string
  strategies: SearchStrategy[]
  total: number
  patents: Patent[]
  warning?: string
}

/** /api/analyze-voc 的响应 */
export interface AnalyzeVocResponse {
  strategies: SearchStrategy[]
  fallback_keywords: string
  warning?: string
}

/** 单道澄清问题 */
export interface ClarifyQuestion {
  id: string
  question: string
  options: string[]
  allow_custom: boolean
}

/** /api/clarify-voc 的响应 */
export interface ClarifyVocResponse {
  questions: ClarifyQuestion[]
  analysis: string
  warning?: string
}

/** /api/enrich-voc 的响应 */
export interface EnrichVocResponse {
  enriched_voc: string
  changes: string[]
}

/** A single VOC idea generated by AI */
export interface VocIdea {
  voc: string
  why: string
}

/** /api/explore-voc 的响应 */
export interface ExploreVocResponse {
  ideas: VocIdea[]
  warning?: string
}

/** /api/upload-doc 的响应 */
export interface UploadDocResponse {
  analysis: string
  doc_name: string
  text_preview: string
  error?: string
}
