export interface Patent {
  patent_number: string
  title: string
  assignee: string
  snippet: string
  publication_date: string
  source: string
  url: string
  country: string
  detail_text?: string
}

export type Step = 'input' | 'patents' | 'report' | 'document'

/** AI 从 VOC 拆解出的单个搜索角度 */
export interface SearchStrategy {
  angle: string      // 中文角度说明
  query: string      // 英文搜索关键词
  rationale: string  // 为什么从这角度搜
}

export interface SearchResponse {
  keywords: string
  strategies: SearchStrategy[]
  total: number
  patents: Patent[]
  warning?: string
}

/** /api/analyze-voc 的响应 */
export interface AnalyzeVocResponse {
  strategies: SearchStrategy[]
  fallback_keywords: string
  warning?: string
}

/** 单道澄清问题 */
export interface ClarifyQuestion {
  id: string
  question: string
  options: string[]
  allow_custom: boolean
}

/** /api/clarify-voc 的响应 */
export interface ClarifyVocResponse {
  questions: ClarifyQuestion[]
  analysis: string
  warning?: string
}

/** /api/enrich-voc 的响应 */
export interface EnrichVocResponse {
  enriched_voc: string
  changes: string[]
}

/** A single VOC idea generated by AI */
export interface VocIdea {
  voc: string
  why: string
}

/** /api/explore-voc 的响应 */
export interface ExploreVocResponse {
  ideas: VocIdea[]
  warning?: string
}

/** /api/upload-doc 的响应 */
export interface UploadDocResponse {
  analysis: string
  doc_name: string
  text_preview: string
  error?: string
}

// ===========================================================================
// VOC Scout + Deep Search 类型
// ===========================================================================

/** ScoutStep 组件的阶段 */
export type ScoutPhase = 'scout_round1' | 'scout_round2' | 'scout_output'

/** Round 1 的一条技术路线 */
export interface ScoutTechRoute {
  id: string
  name: string
  description: string
  companies: string[]
  products: string[]
  key_diff: string
  patent_status_hint: string  // 'expired' | 'active' | 'pending' | ''
  confidence: string           // '★★★' | '★★☆' | '★☆☆'
}

/** Round 1 响应 */
export interface ScoutRound1Response {
  domain_class: string
  confidence: string
  analysis: string
  routes: ScoutTechRoute[]
  contradictions: string[]
}

/** Round 2 中一家公司的详情 */
export interface ScoutCompanyDetail {
  level: string               // 'P0' | 'P1' | 'P2'
  name: string
  tech_summary: string
  patent_number: string
  patent_status: string       // 'expired' | 'active' | 'pending' | ''
  key_ctq: Record<string, string>
  notes: string[]
  source_labels: string[]     // ['[T]', '[P]'] 等
}

/** Round 2 中一条路线的详情 */
export interface ScoutRouteDetail {
  route_id: string
  route_name: string
  companies: ScoutCompanyDetail[]
}

/** Round 2 响应 */
export interface ScoutRound2Response {
  routes: ScoutRouteDetail[]
  contradictions: string[]
  confidence: string
}

/** 三件套工具包输出 */
export interface ScoutOutputResponse {
  companies: {
    priority: {
      level: string
      name: string
      product?: string
      tech?: string
      patent_status?: string
      patent?: string
      note?: string
      source?: string
    }[]
    domestic_reference: string[]
  }
  keywords: {
    core: string[]
    supplement: string[]
    exclude: string[]
  }
  ipc: {
    core: string[]
    supplement: string[]
  }
  fto: {
    notes: string[]
    sweep_query: string
  }
  round_history: Record<string, unknown>[]
  confidence: string
}

/** Deep Search 收敛状态 */
export interface ConvergenceStatus {
  converged: boolean
  total_rounds: number
  new_routes_this_round: number
  new_companies_this_round: number
  reason: string
}

/** Deep Search 完整输出 */
export interface DeepSearchOutput {
  voc: string
  domain_class: string
  confidence: string
  search_path: string
  converged: boolean
  total_rounds: number
  total_companies_found: number
  routes: Record<string, unknown>[]
  ctq_table: Record<string, unknown>[]
  fto: Record<string, unknown>
  recommendation: {
    short_term: string
    medium_term: string
    long_term: string
  }
  convergence: ConvergenceStatus
  user_corrections: Record<string, unknown>[]
  /** Deep Search 返回的专利列表 */
  patents?: Patent[]
}
